#!/bin/sh

buildr test:compile

echo ===============================================================================
exec java -Xmx1024m -Xms256m -server -cp "${SCALA_HOME}/lib/scala-library.jar:target/test/classes" VectorPerf
